### ISSUE TITLE
Steam integration shows as offline. Clicking "retry" doesn't appear to execute anything

### ISSUE THREAD

**Issue by SeaMarc** [gogcom/galaxy-integrations-python-api#99] opened 2019-12-14 00:57 UTC
I went through the steps to integrate my Steam account and it appeared to work, but it shows as offline. I disconnected and tried again and receive the same result. I can log into my steam client outside of GOG. I'm not sure what's wrong. When I click on the "retry" link to try and connect, nothing happens. None of my Steam games show in my GOG library.

**Comment by afreeman** [comment] 2019-12-16 08:13
I had the exact same issue as SeaMarc.  Both Steam and GOG clients had just been updated.

Steam client was running at the time and I confirmed that the Steam service was also running. (set to manual).

One the GOG side, the Galaxy Client Service was confirmed to be running and the Galaxy Communication service was confirmed off (both set to manual).  Tried starting GC manually but it immediately shut itself down with a message that some services will shut down if they are not needed.

Had previously linked Origin to GOG successfully.  Both the Origin service and client were running at the time I tried linking Steam too.  No other platforms are linked to the GOG client.

Its possible that there may be a couple of duplicate games on both Steam and GOG, but they would not be installed.  I can confirm exact details if you wish.

**Comment by Danyelalejandro** [comment] 2019-12-17 02:00
Same problem for me

**Comment by Edstub207** [comment] 2020-01-11 19:48
I've got this issue as well with Xbox Live. Even though all games on that platform show correct.

**Comment by PatchaIT** [comment] 2020-05-01 16:13
I still have this issue.
Anybody solved it, pls?

Thank you.

**Comment by DoktorvonZwitter** [comment] 2020-05-07 06:15
I just got this issue today. It was working fine until today's update.

**Comment by shyney7** [comment] 2020-05-07 11:33
I have the same problem cant link my steam account. It seems to be since the new update? It always tries to connect at startup but then fails. Clicking retry doesn't work either.

**Comment by DoktorvonZwitter** [comment] 2020-05-11 09:46
Okay, Retry did something this time, but now it's stuck on "connecting."

**Comment by gmatiash** [comment] 2020-05-13 21:34
Sane issue here

**Comment by aennok** [comment] 2020-05-21 09:47
I have the same issue, but can it have something to do with Steam's Steam Guard authentication? IT did not ask me for this either.

**Comment by gmatiash** [comment] 2020-05-23 00:47
I was able to mitigate it deleting the integration files and re-downloading it. But after a while the issue comes back.

**Comment by Calorion** [comment] 2020-05-24 15:40
Deleting the integration folder and redownloading didn’t help for me.

**Comment by danmaxis** [comment] 2020-05-25 20:54
Still happens to me.
Sadly, disconnecting and connecting again works until next shutdown or restart.

**Comment by jvkohler** [comment] 2020-06-04 01:16
This happens to me. 

Looking at the logs, authentication on steam's side succeeds but the gog integration errors out processing my userdata. Specifically, it dies trying to look up an appid that steam provided but doesn't seem to exist anymore.

Seems that the plugin just needs to handle exceptions in appid lookups.

Log attached
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8 - trimmed.log](https://github.com/gogcom/galaxy-integrations-python-api/files/4726904/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.-.trimmed.log)

**Comment by jvkohler** [comment] 2020-06-04 02:55
This is a hack that just ignores the KeyError in the logging line and the package lookup rather than finding where the logic is really going wrong. It works for me, but it's not the right way to fix it and it may not work for you. YMMV.

To any devs looking into this, yes it KeyErrors in the logging line before it even starts the loop. For whatever reason you're getting a KeyError in `package_content[str(info.packageid)]`

This is a unified diff to be applied directly to:
Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\protobuf_client.py

[hack-fix-appid-keyerror.diff.txt](https://github.com/gogcom/galaxy-integrations-python-api/files/4727194/hack-fix-appid-keyerror.diff.txt)

**Comment by jpoov13** [comment] 2020-06-07 04:27
This has been bothering me for awhile to the point I straight up uninstalled Galaxy today and reinstalled it to try to fix this. I don't recommend doing that because:

1. It didn't fix it
2. It removed ALL my custom tags; there was no option to retain any custom settings or the like and I spent awhile when I first got Galaxy going through my library creating categories

Until GOG gets their act together and fixes the code, jvkohler's fix worked for me, too, first try. Took a bit to hunt down the file (appdata will help as a better starting point) but after that and backing up the original, magic.

**Comment by TheZAbides** [comment] 2020-06-14 11:47
Same problem here. Started a couple of months ago for me. [I reported the bug to GOG on 5/20/2020](https://mantis2.gog.com/view.php?id=61316) and was notified that the bug was ASSIGNED on 6/2/2020. If you could, report your bug or add notes to that one. Might help them get to the bottom of it.

**Comment by jvkohler** [comment] 2020-06-17 17:22
This is now fixed for me with the better code included in 2.0.16 BETA

**Comment by PatchaIT** [comment] 2020-06-17 17:31
I'm still stuck at 2.0.14 BETA, how to force to check udpate?

**Comment by PatchaIT** [comment] 2020-06-17 18:34
Updated after a few (maybe it was downloading).
But it didn't solved to me.
I also disconnected and reconnected.

**Comment by TheZAbides** [comment] 2020-06-17 20:47
This has now been fixed for me per the latest update. I had to disconnect and reconnect Steam after updating.

**Comment by Calorion** [comment] 2020-06-21 16:57
Could these instructions be simplified for an end-user? Even the simplified instructions on that page don’t make sense to me; I don’t know what "change it with 'localhost' with the quotes” means.

**Comment by mbanczerowski** [comment] 2020-06-26 14:14
Closing as unrelated to this project. See https://github.com/gogcom/galaxy-integrations-python-api/issues/new/choose to find proper place to report Galaxy or plugin issues.

**Closed by mbanczerowski** 2020-06-26 14:14 UTC

**Comment by caniko** [comment] 2021-01-20 17:38
Here is a [link](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/74) to the issue in the right repo!
